/-
  Generated by `scripts/generate-constants.sh`
  Do not edit manually.
-/
import Init.Core

namespace ExtractedValues

def η_min : ℝ := 1.0

def C_bound : ℝ := 2.5

def τ_star : ℝ := 0.1

def K₀ : ℝ := 0.0

def A_param : ℝ := 3.0

end ExtractedValues
