-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — individual constant namespaces (aggregator).

import Multiplicity.UOR.Individuals.Schema
import Multiplicity.UOR.Individuals.Op
import Multiplicity.UOR.Individuals.Resolver
import Multiplicity.UOR.Individuals.Type_
import Multiplicity.UOR.Individuals.Foundation
import Multiplicity.UOR.Individuals.Observable
import Multiplicity.UOR.Individuals.Homology
import Multiplicity.UOR.Individuals.Cohomology
import Multiplicity.UOR.Individuals.Proof
import Multiplicity.UOR.Individuals.Trace
import Multiplicity.UOR.Individuals.Morphism
import Multiplicity.UOR.Individuals.State
import Multiplicity.UOR.Individuals.Reduction
import Multiplicity.UOR.Individuals.Convergence
import Multiplicity.UOR.Individuals.Division
import Multiplicity.UOR.Individuals.Predicate
import Multiplicity.UOR.Individuals.Conformance_
