// TypeScript wrapper for Sedona Spine WASM
// Auto-generated by Antigravity

export async function computeRisk(event: any): Promise<any> {
  // Lazy-load the WASM module and its JS glue
  const wasm = await import('../../pkg/sedona_spine.js');
  const jsonStr = JSON.stringify(event);
  const result = wasm.compute_risk(jsonStr);
  return JSON.parse(result);
}
