name = "SnapKitty"
testDriver = "SnapKittyTests"
defaultTargets = ["SnapKitty"]

[[lean_lib]]
name = "SnapKitty"
path = "./"

[[lean_exe]]
name = "SnapKittyTests"
root = "tests"

[[lean_exe]]
name = "SnapKittyWasm"
root = "src"
