use risc0_zkvm::{Executor, ExecutorEnv, Receipt};
use anyhow::Result;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone)]
pub struct Restrictions {
    pub allowed_tiers: Vec<String>,
    pub requires_rollback_ceiling: bool,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct BudgetToken {
    pub token_id: String,
    pub issuer: String,
    pub budget_limit: u64,
    pub expiry: u64,
    pub provenance_hash: [u8; 32],
    pub restrictions: Restrictions,
    pub iat: u64,
    pub nonce: String,
}

#[derive(Serialize, Deserialize)]
pub struct ComplianceInput {
    pub token: BudgetToken,
    pub proposed_cost: u64,
    pub rollback_loaded: bool,
}

// In a real build, we'd include the ELF generated by cargo risczero build
// const GUEST_ELF: &[u8] = include_bytes!("../guest/target/riscv32im-risc0-zkvm-elf/docker/release/guest");
const GUEST_ELF: &[u8] = b"placeholder"; 

pub fn prove_compliance(input: ComplianceInput, rollback_receipt: Option<Receipt>) -> Result<Receipt> {
    let mut env_builder = ExecutorEnv::builder().write(&input)?;
    
    if let Some(r) = rollback_receipt {
        env_builder.add_assumption(r.claim())?;  // Composition
    }
    
    let env = env_builder.build()?;
    let mut exec = Executor::from_elf(env, GUEST_ELF)?;
    let session = exec.run()?;
    let receipt = session.prove()?;
    Ok(receipt)
}
